### ISSUE TITLE
Wrong location for rendering settings

### ISSUE THREAD

**Issue by alan-null** [Sitecore/Habitat#137]
**How to reproduce:**
1. Navigate to `/sitecore/content/Habitat` in CE
2. Select item `/sitecore/content/Habitat`
3. Right click on item: `/sitecore/content/Habitat/Settings`
4. Create new rendering settings

**Actual result:**
Settings will be created under currently selected item (`/sitecore/content/Habitat`), not under settings (`/sitecore/content/Habitat/Settings`).

**Expected result:**
Rendering settings should be created under `Settings` root.

**Comment by VyacheslavStashchenko** [comment]
Issue was registered in tfs.
Bug #37756: Wrong location for rendering settings.

**Comment by stasmaxymov** [comment]
Hi @alan-null ,
Your pull request was reverted, because it creates another issue in rendering settings.
If you try to add rendering setting using command in Insert chunk under Home tab, you will get an error.
Anyway I created a branch: [bug/rendering-settings-wrong-location](https://github.com/Sitecore/Habitat/tree/bug/rendering-settings-wrong-location) with your changes.
You can send a proper fix to this branch or just wait when the issue will be fixed from our side.

**Comment by alan-null** [comment]
Hi @stasmaxymov,
Problem fixed.

**Comment by alan-null** [comment]
Merged to master #140
