### ISSUE TITLE
Theming as part of the project?

### ISSUE THREAD

**Issue by donavonyoung** [Sitecore/Habitat#149]
Just a general question. not really an issue. Is there a reason theming is part of the the foundation vs being incorporated into the websites projects (projects/habitat)?

**Comment by Eldblom** [comment]
I see your point - great question. 
If you think of theming as the CSS only, i.e. the final design touches of a website, it would sit in the project layer. This typically requires knowledge of all the components and layout of the pages and holistically designs the page as a whole.
But in order to create a feature - with the views and HTML, the feature has to know about the overall theming guidelines, i.e. the frontend framework which is applied across the views. In other words, the CSS classes defined in the Foundation layer needs to be as generic and semantic as possible to allow you to use the across features and projects (just like a Frontend framework like bootstrap or foundation is). Where as the CSS in the project layer can be more high level and focus on the holistic visual design of pages. Therefore conceptually the design sort of sits in both places.

If you have a project where many project modules or websites share the same features, this split makes a lot of sense. In a one website scenario the CSS would probably be in the project layer and you would live with the features having a certain knowledge of the CSS classes applied to the HTML.

Hope it makes sense :-)

**Comment by Eldblom** [comment]
BTW, I totally recommend you to join the Sitecore Community Slack channel for Habitat. Great place for these kinds of discussions. 
If you are not there already, reach out to @akshaysura13 or @mike_i_reynolds on Twitter for an invite.

**Comment by donavonyoung** [comment]
Thanks for the in depth response and heads up on the slack group. I will reach out to them for an invite. Hope to continue the discussion there.
