### ISSUE TITLE
Unicorn error on non-local install

### ISSUE THREAD

**Issue by PepeLeffue** [Sitecore/Habitat#338]
I have a dev environment that is not a complete sitecore install but is a databse install on a dev db and an application install on a dev app server.  I followed the instructions and used the designated versions of sitecore.  Sitecore install was named 'platform' and I bound habitat.dev.local to the platform web application.

Changes made were:
zHabitatDevSettings - 
`<sc.variable name="sourceFolder" value="D:\www\Habitat\src" />
    <sc.variable name="rootHostName" value="platform" />`
gulpconfig -
`var instanceRoot = "\\\\{app server ip}\\d$\\www\\platform"`
publishsetings.target -
`<publishUrl>http://habitat.dev.local</publishUrl>`

When it gets to step 5 (unicorn) it just gives me the "Unable to resolve serialized item for included root path master:/sitecore/system/Settings/Feature. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?"  

Can habitat be set up on an instance of sitecore that is both non-local & where the db and app servers are seperate?  Thanks.

**Comment by YggY** [comment]
I tried a non-local install (with DB & App on 1 server), where my source was local. Unfortunately the way Unicorn works is that it automatically serializes the Sitecore items to disk, more specifically: to your source control folder. The setting that controls this location is the sourceFolder variable in zHabitatDevSettings.config.

The difficulty lies here: this config lives in your web application (IIS on App server), and the variable points to your source control folder (in our case: on our local machine). You can try to share your source folder and point the config to the applicable network path... ór move your source folder to the app server and share that to your local machine and open the VS solution over the network. 

Either way: you'll end up with lots of network traffic. In my case it was not feasible because of 1: bandwidth and 2: my laptop and the server are not in the same AD (and I'm not about to open up a share to everyone)

Please let us know if you manage to make it work, I'm curious if it's workable.

**Comment by jeanfrancoislarente** [comment]
I read recently that you would need to include your .yml files in your deployment. Then when you deploy from your local source to your remote server the .yml files are included in the server deployment.

Not sure if that's feasible in your case. Maybe another script / job to separately just copy all *.yml files (in their proper hierarchy? When you deploy from local you'd have a post deploy action to copy all of the .yml files to your server.

**Comment by YggY** [comment]
Well of course, if you're doing deployments, you should take along your sitecore items as well. However, I would say that while doing development, you wouldn't want to do deployments continuously to your own environment: you'd be better off having that done completely automatically by Unicorn.

**Comment by jeanfrancoislarente** [comment]
Fair enough. My suggestion for the OP still stands though, you're likely to get better and more specific help by creating an issue on the Unicorn GitHub project.
