### ISSUE TITLE
Update installation instructions for SIF scripts on v9

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Habitat#386]
Downloading prerequisites, configuring `settings`, using `install-xp0`, and usefulness of `uninstall-xp0` for cleaning up partial installs or removing Habitat entirely.

**Comment by VeromcaChang** [comment]
Thanks for the tips! BTW, I only have one computer and have installed XP 9 update 1 and Commerce 9 update 1. I want to install Habitat on the same machine with another solr and another third party tools, because there is no advice for installing Habit on a installed XP in instructions. Will you think it's a good idea?

**Comment by nickwesselman** [comment]
Hi @VeromcaChang -- glad this backlog item was useful for you. :) For usage questions though, would you mind posting on [Sitecore Stackexchange](https://sitecore.stackexchange.com/questions), or the [Sitecore Community Slack](http://bit.ly/SitecoreSlackSignup)? I'd like to keep GitHub limited to bug reports, feature requests, etc. Thanks!

**Comment by VeromcaChang** [comment]
Ok. I got it.
