### ISSUE TITLE
Migrate to PackageReference for all nuget dependencies, if feasible

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Habitat#406]
Move away from `packages.config` and use VS17 support for `PackageReference`.

https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

Note the limitations of `PackageReference` above, may want to reconsider if dependency packages will be troublesome without the noted features.

See #404

**Comment by jeanfrancoislarente** [comment]
@nickwesselman fwiw I just did that for HabitatHome and used NuGet PackageReference Upgrader VS Extension. Made the process very quick and completely painless (right-click on packages.config and select the extension

https://marketplace.visualstudio.com/items?itemName=CloudNimble.NuGetPackageReferenceUpgrader

**Comment by jeanfrancoislarente** [comment]
Upgraded all projects to use PackageReference instead of packages.config. 
Compiled -> good
install -> deploy from scratch -> good

Unit tests: https://pasteboard.co/HsSFG8R.png
Two are failing but unfortunately I didn't run the tests _prior_ to the upgrade so I'm not sure if it's from the upgrade or existed before. Creating a PR.
