### ISSUE TITLE
Messaging user is not configurable

### ISSUE THREAD

**Issue by Spotnick2** [Sitecore/Habitat#437]
**Describe the bug**
Trying to install the latest version of the v9 branch won't let me install because it's trying to create [messaginguser] with a password not long enough for the entreprise password policy and I can't bypass it. Unlike the others, the [messaginguser] is not configurable in settings.ps1

**Sitecore Version**
9.0.2  rev 180604

**To Reproduce**
1. run script uninstall-xp0.ps1
2. run script install-xp0.ps1
3. See error

**Expected behavior**
Should install properly, it was with version 9.0.0

Expecting those variables in settings.ps1

$XConnectSqlMessagingUser = "messaginguser"
$XConnectSqlMessagingPassword = "Test12345"

**Screenshots**
![image](https://user-images.githubusercontent.com/42148291/43725546-d14d95bc-996a-11e8-8c2a-45b0726bebbf.png)

**Comment by nickwesselman** [comment]
Hello @Spotnick2, thanks for reporting. However the only SQL u/p currently configurable in `settings.ps1` is the SQL Admin password -- otherwise the `install-xp0.ps1` is using the default usernames and passwords from `sitecore-XP0.json` and `xconnect-xp0.json`. Perhaps you previously created the other users with a password that meets your organization's requirements.

We can consider a feature request to make the other SQL passwords configurable in `settings.ps1` (perhaps just a single user/password) but meanwhile, a workaround would be to edit `install-xp0.ps1` and add the u/p parameters to the invocations of `Install-SitecoreConfiguration`. You can find the parameters in the SIF configuration json files.

**Comment by nickwesselman** [comment]
One slight correction -- the `$XConnectSqlCollectionUser` setting does allow configuring the XConnect database. However none of the CMS databases (including master, web, core, EXM, messaging) currently can be configured with a u/p.

**Comment by jeanfrancoislarente** [comment]
Handled in 9.1 "Single-developer" install. No longer needed.
